mineral_catalog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
import debug_toolbar

from . import views

urlpatterns = [
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('minerals.urls', namespace='home')),
    url(r'^__debug__/', include(debug_toolbar.urls)),
]

urlpatterns += staticfiles_urlpatterns()

minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.mineral_list, name='list'),
    url(r'^search/$', views.search, name='search'),
    url(r'^(?P<letter>[a-zA-Z])/$', views.mineral_letter, name='letter'),
    url(r'^(?P<group>[a-zA-Z\s]+)/$', views.search_group, name='groups'),
    url(r'^(?P<pk>\d+)/$', views.mineral_detail, name='detail'),
]

minerals/models.py
from django.db import models
import json


class Mineral(models.Model):
    name = models.CharField(max_length=100, unique=True)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=755)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)
    group = models.CharField(max_length=255)

    class Meta:
        ordering = ['name',]

    def __str__(self):
        return self.name

    @classmethod
    def add_minerals_to_database(cls):
        with open('minerals.json', encoding='utf-8', mode='r') as file:
            minerals = json.load(file)
            for mineral in minerals:
                Mineral(
                    name=mineral.get('name'),
                    image_filename=mineral.get('image filename', ''),
                    image_caption=mineral.get('image caption', ''),
                    category=mineral.get('category', ''),
                    formula=mineral.get('formula', ''),
                    strunz_classification=mineral.get('strunz classification', ''),
                    crystal_system=mineral.get('crystal system', ''),
                    unit_cell=mineral.get('unit cell', ''),
                    color=mineral.get('color', ''),
                    crystal_symmetry=mineral.get('crystal symmetry', ''),
                    cleavage=mineral.get('cleavage', ''),
                    mohs_scale_hardness=mineral.get('mohs scale hardness', ''),
                    luster=mineral.get('luster', ''),
                    streak=mineral.get('streak', ''),
                    diaphaneity=mineral.get('diaphaneity', ''),
                    optical_properties=mineral.get('optical properties', ''),
                    refractive_index=mineral.get('refractive index', ''),
                    crystal_habit=mineral.get('crystal habit', ''),
                    specific_gravity=mineral.get('specific gravity', ''),
                    group = mineral.get('group', ''),
                ).save()

mineral_catalog/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'index.html')

minerals/views.py
from django.shortcuts import render

from .models import Mineral


def mineral_list(request):
    minerals = Mineral.objects.all()
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def mineral_detail(request, pk):
    mineral = Mineral.objects.get(pk=pk)
    return render(request, 'minerals/mineral_detail.html', {'mineral': mineral})


def mineral_letter(request, letter):
    minerals = Mineral.objects.filter(name__istartswith=letter.lower())
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals, 'active_letter':letter})


def search(request):
    term = request.GET.get("q")
    minerals = Mineral.objects.filter(name__icontains=term)
    return render(request, 'minerals/mineral_list.html', {'minerals': minerals})


def search_group(request,group):
    minerals = Mineral.objects.filter(group__icontains=group)
    return render(request,'minerals/mineral_list.html', {'minerals':minerals})

minerals/templates/minerals/mineral_detail.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
<div class="grid-100 mineral__container">
<h1 class="mineral__name">{{mineral.name|title}}</h1>
  <div class="mineral__image-bg">
    <img class="mineral__image" src="{% static 'img' %}/{{mineral.name}}.jpg" alt="{{ mineral.name|title }}">
        <p class="mineral__caption">{{mineral.image_caption}}</p>
      </div>
<div class="mineral__table-container">
        <table class="mineral__table">
          <tr>
            <td class="mineral__category">Category</td>
            <td>{{mineral.category|title}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Formula</td>
            <td class="mineral__formula">{{mineral.formula|safe}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Strunz Classification</td>
            <td>{{mineral.strunz_classification|title}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Unit Cell</td>
            <td>{{mineral.unit_cell|title}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Color</td>
            <td>{{mineral.color|title}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Crystal Habit</td>
            <td>{{mineral.crystal_habit|title}}</td>
          </tr>
          <tr>
            <td class="mineral__category">Mohs Scale Hardness</td>
            <td>{{mineral.mohs_scale_hardness|title}}</td>
          </tr>
           <tr>
            <td class="mineral__category">Group</td>
            <td>{{mineral.group|title}}</td>
          </tr>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

minerals/templates/minerals/mineral_list.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block content %}
<div class="grid-100">
    <ul class="minerals__container">
    {% for mineral in minerals %}
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }} </a>
        </li>
    {% endfor %}
      </ul>
    </div>
{%endblock%}

minerals/templates/minerals/mineral_nav.html
{% for group in groups %}
    <a href="{% url 'minerals:groups' group=group%}">{{ group }}</a>
{% endfor %}

templates/index.html
{% extends "layout.html" %}
{% block content %}
 <div class="grid-100">
     {% for mineral in minerals %}
      <ul class="minerals__container">
        <li class="minerals__item">
          <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral.name }} </a>
        </li>
        {% endfor %}
      </ul>
    </div>

{% endblock %}

templates/layout.html
{% load static from staticfiles %}
{% load mineral_extras %}

<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Macky's Minerals: A magnificant catalog of minerals</title>
  <meta name="description" content="">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
  <div class="bounds">
    <div class="grid-100">
      <a href="/">
        <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
          <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
          <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
          <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
        </svg>
        <h1 class="logo__name text-centered">Macky's Minerals</h1>
      </a>
      <p class="logo__text text-centered">They're not rocks!</p>
    </div>
    <nav class="top-bar" role="navigation">
       <section class="top-bar-left">
          <form action="{% url 'minerals:search' %}" method="GET">
            <input type="search" name="q">
            <button type="button" class="secondary small button">Search</button>
                </form>
       </section>
    </nav>

<div>
</div>
    <div class="grid-100">
      <h2>Search Rock By Letter:</h2>
      {% for letter in "abcdefghijklmnopqrstuvwxyz" %}
        {% if letter == active_letter %}
      <strong><a href="{% url 'minerals:letter' letter=letter %}">{{ letter }}</a></strong>
        {% else %}
        <a href="{% url 'minerals:letter' letter=letter %}">{{ letter }}</a>
        {% endif %}
      {% endfor %}
      <br>
      <br>
    </div>
    <div class="grid-100">
      <h2>Search Rock By Category:</h2>
      {% nav_minerals_list %}
      <br>
      <br>
    </div>
    <div>
   {% block content %}{% endblock %}
    </div>
  </div>
  <div class="minerals__random">
    <a class="minerals__anchor" href="">Show random mineral</a>
  </div>
</body>
</html>